
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action LoginAction;
	private global::Gtk.Action LoginAction1;
	private global::Gtk.Action LogoutAction;
	private global::Gtk.Action UpdateAction;
	private global::Gtk.Action CheckOfUpdatesAction;
	private global::Gtk.Action ExitAction;
	private global::Gtk.Action TasksAction;
	private global::Gtk.Action NewTaskAction;
	private global::Gtk.Action EditTaskAction;
	private global::Gtk.Action MinimizeToTaskBarAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.Notebook notebook2;
	private global::Gtk.VBox vbox6;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView textview2;
	private global::Gtk.HBox hbox2;
	private global::Gtk.ComboBox combobox1;
	private global::Gtk.Button button2;
	private global::Gtk.Button button3;
	private global::Gtk.Label label2;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Label label5;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textview1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Entry entry2;
	private global::Gtk.Button button1;
	private global::Gtk.Label label3;
	private global::Gtk.VBox vbox5;
	private global::Gtk.VBox vbox7;
	private global::Gtk.DrawingArea drawingarea3;
	private global::Gtk.VBox vbox8;
	private global::Gtk.Label label1;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Entry entry1;
	private global::Gtk.Button button4;
	private global::Gtk.DrawingArea drawingarea4;
	private global::Gtk.Label label4;
	private global::Gtk.VBox vbox3;
	private global::Gtk.DrawingArea drawingarea1;
	private global::Gtk.VBox vbox9;
	private global::Gtk.Label label9;
	private global::Gtk.ComboBoxEntry comboboxentry1;
	private global::Gtk.Button button5;
	private global::Gtk.DrawingArea drawingarea2;
	private global::Gtk.Label label6;
	private global::Gtk.VBox vbox4;
	private global::Gtk.DrawingArea drawingarea5;
	private global::Gtk.Label label10;
	private global::Gtk.DrawingArea drawingarea6;
	private global::Gtk.Label label7;
	private global::Gtk.Statusbar statusbar1;
	private global::Gtk.Label label8;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action (
			"FileAction",
			global::Mono.Unix.Catalog.GetString("File"),
			null,
			null
		);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.LoginAction = new global::Gtk.Action (
			"LoginAction",
			global::Mono.Unix.Catalog.GetString("Login"),
			null,
			null
		);
		this.LoginAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Login");
		w1.Add (this.LoginAction, null);
		this.LoginAction1 = new global::Gtk.Action (
			"LoginAction1",
			global::Mono.Unix.Catalog.GetString("Login"),
			null,
			null
		);
		this.LoginAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Login");
		w1.Add (this.LoginAction1, null);
		this.LogoutAction = new global::Gtk.Action (
			"LogoutAction",
			global::Mono.Unix.Catalog.GetString("Logout"),
			null,
			null
		);
		this.LogoutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Logout");
		w1.Add (this.LogoutAction, null);
		this.UpdateAction = new global::Gtk.Action (
			"UpdateAction",
			global::Mono.Unix.Catalog.GetString("Update"),
			null,
			null
		);
		this.UpdateAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Update");
		w1.Add (this.UpdateAction, null);
		this.CheckOfUpdatesAction = new global::Gtk.Action (
			"CheckOfUpdatesAction",
			global::Mono.Unix.Catalog.GetString("Check of updates"),
			null,
			null
		);
		this.CheckOfUpdatesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Check of updates");
		w1.Add (this.CheckOfUpdatesAction, null);
		this.ExitAction = new global::Gtk.Action (
			"ExitAction",
			global::Mono.Unix.Catalog.GetString("Exit"),
			null,
			null
		);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction, null);
		this.TasksAction = new global::Gtk.Action (
			"TasksAction",
			global::Mono.Unix.Catalog.GetString("Tasks"),
			null,
			null
		);
		this.TasksAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tasks");
		w1.Add (this.TasksAction, null);
		this.NewTaskAction = new global::Gtk.Action (
			"NewTaskAction",
			global::Mono.Unix.Catalog.GetString("New Task"),
			null,
			null
		);
		this.NewTaskAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New Task");
		w1.Add (this.NewTaskAction, null);
		this.EditTaskAction = new global::Gtk.Action (
			"EditTaskAction",
			global::Mono.Unix.Catalog.GetString("Edit Task"),
			null,
			null
		);
		this.EditTaskAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit Task");
		w1.Add (this.EditTaskAction, null);
		this.MinimizeToTaskBarAction = new global::Gtk.Action (
			"MinimizeToTaskBarAction",
			global::Mono.Unix.Catalog.GetString("Minimize to task bar"),
			null,
			null
		);
		this.MinimizeToTaskBarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Minimize to task bar");
		w1.Add (this.MinimizeToTaskBarAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Drone Client");
		this.Icon = global::Stetic.IconLoader.LoadIcon (
			this,
			"gtk-dialog-authentication",
			global::Gtk.IconSize.Menu
		);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='ExitAction' action='ExitAction'/><menuitem name='MinimizeToTaskBarAction' action='MinimizeToTaskBarAction'/></menu><menu name='LoginAction' action='LoginAction'><menuitem name='LoginAction1' action='LoginAction1'/><menuitem name='LogoutAction' action='LogoutAction'/></menu><menu name='UpdateAction' action='UpdateAction'><menuitem name='CheckOfUpdatesAction' action='CheckOfUpdatesAction'/></menu><menu name='TasksAction' action='TasksAction'><menuitem name='NewTaskAction' action='NewTaskAction'/><menuitem name='EditTaskAction' action='EditTaskAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook2 = new global::Gtk.Notebook ();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 0;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textview2 = new global::Gtk.TextView ();
		this.textview2.CanFocus = true;
		this.textview2.Name = "textview2";
		this.textview2.Editable = false;
		this.GtkScrolledWindow1.Add (this.textview2);
		this.vbox6.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GtkScrolledWindow1]));
		w4.Position = 0;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.combobox1 = global::Gtk.ComboBox.NewText ();
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("Tasks For Master                                 "));
		this.combobox1.Name = "combobox1";
		this.combobox1.Active = 0;
		this.hbox2.Add (this.combobox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.combobox1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Start/Finish");
		this.hbox2.Add (this.button2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button2]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("RANDOM BUTTON");
		this.hbox2.Add (this.button3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button3]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox6.Add (this.hbox2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox2]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.notebook2.Add (this.vbox6);
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Tasks");
		this.notebook2.SetTabLabel (this.vbox6, this.label2);
		this.label2.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Chat with Master and other drones");
		this.vbox2.Add (this.label5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label5]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.textview1.Editable = false;
		this.GtkScrolledWindow.Add (this.textview1);
		this.vbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
		w12.Position = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.hbox1.Add (this.entry2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entry2]));
		w13.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Send");
		this.hbox1.Add (this.button1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button1]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox2.Add (this.hbox1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		this.notebook2.Add (this.vbox2);
		global::Gtk.Notebook.NotebookChild w16 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.vbox2]));
		w16.Position = 1;
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Chat");
		this.notebook2.SetTabLabel (this.vbox2, this.label3);
		this.label3.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.drawingarea3 = new global::Gtk.DrawingArea ();
		this.drawingarea3.Name = "drawingarea3";
		this.vbox7.Add (this.drawingarea3);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.drawingarea3]));
		w17.Position = 0;
		this.vbox5.Add (this.vbox7);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox7]));
		w18.Position = 0;
		// Container child vbox5.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("What would you like to report to Master and Mistress?");
		this.vbox8.Add (this.label1);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label1]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.hbox3.Add (this.entry1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entry1]));
		w20.Position = 0;
		this.vbox8.Add (this.hbox3);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox3]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("Report");
		this.vbox8.Add (this.button4);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.button4]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		this.vbox5.Add (this.vbox8);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox8]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.drawingarea4 = new global::Gtk.DrawingArea ();
		this.drawingarea4.Name = "drawingarea4";
		this.vbox5.Add (this.drawingarea4);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.drawingarea4]));
		w24.Position = 2;
		this.notebook2.Add (this.vbox5);
		global::Gtk.Notebook.NotebookChild w25 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.vbox5]));
		w25.Position = 2;
		// Notebook tab
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Report");
		this.notebook2.SetTabLabel (this.vbox5, this.label4);
		this.label4.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.drawingarea1 = new global::Gtk.DrawingArea ();
		this.drawingarea1.Name = "drawingarea1";
		this.vbox3.Add (this.drawingarea1);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.drawingarea1]));
		w26.Position = 0;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("What would you like to ask Master and Mistress permission to do?");
		this.vbox9.Add (this.label9);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.label9]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.comboboxentry1 = global::Gtk.ComboBoxEntry.NewText ();
		this.comboboxentry1.Name = "comboboxentry1";
		this.vbox9.Add (this.comboboxentry1);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.comboboxentry1]));
		w28.Position = 1;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button ();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("Ask");
		this.vbox9.Add (this.button5);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.button5]));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		this.vbox3.Add (this.vbox9);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox9]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.drawingarea2 = new global::Gtk.DrawingArea ();
		this.drawingarea2.Name = "drawingarea2";
		this.vbox3.Add (this.drawingarea2);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.drawingarea2]));
		w31.Position = 2;
		this.notebook2.Add (this.vbox3);
		global::Gtk.Notebook.NotebookChild w32 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.vbox3]));
		w32.Position = 3;
		// Notebook tab
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Ask Permission");
		this.notebook2.SetTabLabel (this.vbox3, this.label6);
		this.label6.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.drawingarea5 = new global::Gtk.DrawingArea ();
		this.drawingarea5.Name = "drawingarea5";
		this.vbox4.Add (this.drawingarea5);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.drawingarea5]));
		w33.Position = 0;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Here you can launch minigames developed by The Hive. This part isn't ready yet.");
		this.vbox4.Add (this.label10);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label10]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.drawingarea6 = new global::Gtk.DrawingArea ();
		this.drawingarea6.Name = "drawingarea6";
		this.vbox4.Add (this.drawingarea6);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.drawingarea6]));
		w35.Position = 2;
		this.notebook2.Add (this.vbox4);
		global::Gtk.Notebook.NotebookChild w36 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.vbox4]));
		w36.Position = 4;
		// Notebook tab
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Extras");
		this.notebook2.SetTabLabel (this.vbox4, this.label7);
		this.label7.ShowAll ();
		this.vbox1.Add (this.notebook2);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook2]));
		w37.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("label8");
		this.statusbar1.Add (this.label8);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.label8]));
		w38.Position = 1;
		w38.Expand = false;
		w38.Fill = false;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w39.Position = 2;
		w39.Expand = false;
		w39.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 461;
		this.DefaultHeight = 546;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
